"""Computer Vision — YOLOv11 training pipeline (Ultralytics).

NOTE — this is a real, runnable training script, but it CANNOT be trained in a
hackathon window without (a) a labeled dataset and (b) a GPU. The pipeline,
class list, and data layout are production-shaped; bring your own images/labels
(e.g. from Roboflow PPE datasets) under datasets/ppe/.

Expected layout:
    datasets/ppe/
      images/{train,val}/*.jpg
      labels/{train,val}/*.txt     # YOLO format
      data.yaml                    # generated by write_data_yaml()

Usage: python -m cv.train_yolo
Artifact: runs/detect/train/weights/best.pt
"""
from __future__ import annotations
import os

CLASSES = ["helmet", "no_helmet", "gloves", "no_gloves", "vest", "no_vest",
           "person", "smoke", "fire"]
DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "datasets", "ppe")


def write_data_yaml():
    os.makedirs(DATA_DIR, exist_ok=True)
    path = os.path.join(DATA_DIR, "data.yaml")
    with open(path, "w") as fh:
        fh.write("path: " + os.path.abspath(DATA_DIR) + "\n")
        fh.write("train: images/train\nval: images/val\n")
        fh.write(f"nc: {len(CLASSES)}\n")
        fh.write("names: " + str(CLASSES) + "\n")
    print("wrote", path)
    return path


def train(epochs: int = 50, imgsz: int = 640):
    from ultralytics import YOLO
    data_yaml = write_data_yaml()
    model = YOLO("yolo11n.pt")  # nano base; swap for yolo11s/m for accuracy
    model.train(data=data_yaml, epochs=epochs, imgsz=imgsz, batch=16)
    print("training complete -> runs/detect/train/weights/best.pt")


if __name__ == "__main__":
    train()
